#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 repo_name"
    exit 1
fi

dir=/srv/elixir-data/$1

export LXR_REPO_DIR=$dir/repo
export LXR_DATA_DIR=$dir/data

cd $LXR_REPO_DIR
git fetch --all --tags

python3 /usr/local/elixir/update.py 64
